### ISSUE TITLE
DbSet of an interface type

### ISSUE THREAD

**Issue by yaseralnajjar** [BlueshiftSoftware/EntityFrameworkCore#13]
When adding a dbset like this:

```
public DbSet<IOwner> Owners { get; set; }
```

This exception occurs:
```
ArgumentException: The entity type 'EFMongoDemo.Web.Models.IOwner' provided for the argument 'clrType' must be a reference type.
Microsoft.EntityFrameworkCore.Utilities.Check.ValidEntityType(Type value, string parameterName)
```

I know that using a base type is a solution, but it would just much better for scaling apps to use interfaces (not sure if possible).

**Comment by crhairr** [comment]
This is a limitation of [EF Core](https://github.com/aspnet/EntityFrameworkCore/blob/554d2889c991f6504b1d9f383b423f352021e2ee/src/EFCore/Metadata/Internal/EntityType.cs#L74). If you would like for EF Core to support non-instantiable entity types, please raise the issue in [their repository](https://github.com/aspnet/EntityFrameworkCore/issues).

Please keep in mind that EFCore-MongoDB is a _provider_ for MongoDB built on top of EF Core.
