### ISSUE TITLE
.ToTable() equivalent

### ISSUE THREAD

**Issue by dannotsys** [BlueshiftSoftware/EntityFrameworkCore#18]
Hi Chris, is there some equivalent way of setting the mongodb collection name on the OnModelCreating method, like the relational database variant Microsoft.EntityFrameworkCore.RelationalEntityTypeBuilderExtensions.ToTable()?

**Comment by dannotsys** [comment]
I have used the .Entity<MyClass>().MongoDb().CollectionName property but that does´t seem the proper way of doing it, right?

**Comment by crhairr** [comment]
You can also use the [`MongoCollectionAttribute`](https://github.com/crhairr/EntityFrameworkCore.MongoDb/blob/a465954e756865c771bed903b054d49acfe5db65/src/Blueshift.EntityFrameworkCore.MongoDB/Annotations/MongoCollectionAttribute.cs#L12) if you prefer declarative/aspect-oriented data modeling, or the [`EntityTypeBuilder.ForMongoDbFromCollection`](https://github.com/crhairr/EntityFrameworkCore.MongoDb/blob/a465954e756865c771bed903b054d49acfe5db65/src/Blueshift.EntityFrameworkCore.MongoDB/Metadata/Builders/MongoDbEntityTypeBuilderExtensions.cs#L20) extension method if you prefer the fluent API for `OnModelCreating`.

**Comment by dannotsys** [comment]
Amazing, thanks!
