### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by tomasjurasek** [BlueshiftSoftware/EntityFrameworkCore#20]
Hi,
i cannot install your package on clean console app (.net core 2.0).

Error:
"Unable to find package Microsoft.EntityFrameworkCore with version (>= 2.1.0-preview1-28051)"
"Unable to find package Microsoft.Extensions.Configuration with version (>= 2.1.0-preview1-28051)"¨

Thanks

**Comment by crhairr** [comment]
If you were following the [Getting Started](https://github.com/crhairr/EntityFrameworkCore.MongoDb/wiki/Getting-Started) wiki, you might have been using the old ASP.NET Core MyGet package source, which is no longer in use. Either way, I have just updated the wiki.

Please make sure that your NuGet.config has the following source in it:

```XML
<add key="AspNetCore" value="https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json" />
```

**Comment by tomasjurasek** [comment]
Oh, sorry i missed this line.
Thanks
