### ISSUE TITLE
Wiki Getting Started Installing EFCore-MongoDb error

### ISSUE THREAD

**Issue by qgxcry** [BlueshiftSoftware/EntityFrameworkCore#38]
![image](https://user-images.githubusercontent.com/13807716/53476048-74361c80-3aac-11e9-9d4a-0cf9a0d2e67f.png)
change:
nuget sources add -name EFCore-MongoDb -Source https://www.myget.org/gallery/efcore-mongodb/api/v3/index.json

**Comment by crhairr** [comment]
Good catch! Updated.
